app/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import db

class User(db.Model, UserMixin):
    __tablename__ = 'usuario'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(256), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    usuario_profesion=db.Column(db.String(128),nullable=False)
    is_admin = db.Column(db.Boolean, default=False)
    def __repr__(self):
        return f'<User {self.email}>'
    def set_password(self, password):
        self.password = generate_password_hash(password)
    def check_password(self, password):
        return check_password_hash(self.password, password)
    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()
    @staticmethod
    def get_by_id(id):
        return User.query.get(id)
    @staticmethod
    def get_by_email(email):
        return User.query.filter_by(email=email).first()
    def delete(self):
        db.session.delete(self)
        db.session.commit()
    @staticmethod
    def get_all():
        return User.query.all()
    


        

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,BooleanField,SelectField
from wtforms.validators import DataRequired, Email, Length
class SignupForm(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired(message="el campo es obligatorio"), Length(min=3,max=64,message="El campo es oblogatorio y debe tener entre 3 a 64 caracteres")])
    password = PasswordField('Password', validators=[DataRequired(message="el campo es obligarorio")])
    email = StringField('Email', validators=[DataRequired(), Email()])
    usuario_profesion=SelectField('Profesión de usuario',choices=[('medico','medico'),("enfermero","enfermero")])
    submit = SubmitField('Registrar')  



class LoginForm(FlaskForm):
    email = StringField('Email    ', validators=[DataRequired(message="el campo es obligatorio")])
    password = PasswordField('Password', validators=[DataRequired("el campo es obligatorio")])
    remember_me = BooleanField('Recuérdame')
    submit = SubmitField('Ingresar')
    

app/user/__init__.py
from flask import Blueprint

user_bp = Blueprint('user', __name__, template_folder='templates')

from . import routes

app/user/routes.py
from flask import render_template, redirect, url_for, request,current_app,flash
from flask_login import current_user, login_user, logout_user,login_required
from werkzeug.urls import url_parse
from app import login_manager
from . import user_bp
from .forms import SignupForm, LoginForm
from .models_registro_logeo import Useradmin


@user_bp.route('/ingresar', methods=['GET', 'POST'])
def login():
    """_Funcion de ingreso_

    Returns:
        _type_: _Si ya esta registrado lo manda al la página de usuarios
                 En caso de no estarlo, _
    """

    
    if current_user.is_authenticated:
        return render_template('user/index_user.html', user=current_user)
       
    form = LoginForm()
    if (form.validate_on_submit()):
        
        user = Useradmin.get_by_email(form.email.data)
        if user is not None:
            clave=user.check_password(form.password.data)
            if clave:
                login_user(user, remember=form.remember_me.data)
                succes_message="Bienvenido{}".format(user.name)
                next_page = request.args.get('next')
                if not next_page or url_parse(next_page).netloc != '':
                    next_page = url_for('user.index')
                return redirect(next_page)
            else:
                 current_app.logger.info('La contraseña no es la indicada')
                 flash('La contraseña no es la indicada ',"alert alert-danger")
                 return redirect(url_for("user.login"))
        else:
            
            userio=form.email.data
            #error =
            current_app.logger.info('el usuario no esta registrado')
            flash( f'El usuario {userio} no esta registrado',"alert alert-danger")
            return redirect(url_for("user.login"))
            
    return render_template('user/ingresar.html', form=form)

@user_bp.route("/registrar", methods=["GET", "POST"])
def registrar():
    if current_user.is_authenticated:
        return redirect(url_for('user.index'))
    form = SignupForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        usuario_profesion=form.usuario_profesion.data
        user = Useradmin.get_by_email(email)
        if user is not None:
            flash(f'El email {email} ya está siendo utilizado',"alert alert-danger")
            
        else:
            user = Useradmin(name=name, email=email,usuario_profesion=usuario_profesion)
            user.set_password(password)
            user.save()
            login_user(user, remember=True)
            next_page = request.args.get('next', None)
            
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('user.index')
            return redirect(next_page)
    return render_template("user/registrar.html", form=form)

@user_bp.route('/user', methods=['GET', 'POST'])
@login_required
def index():
    return render_template("user/index_user.html")


@user_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('public.index'))


@login_manager.user_loader
def load_user(user_id):
    return Useradmin.get_by_id(int(user_id))

app/user/templates/user/base_usuarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/style.css')}}">
</head>
<body>
   
  
  {% include "navbarusuarios.html" %}
 

  {% block content %}

  {% endblock %}

  {% include "contacto.html" %}
 

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.3.3/chart.min.js" integrity="sha512-fMPPLjF/Xr7Ga0679WgtqoSyfUoQgdt8IIxJymStR5zV3Fyb6B3u/8DcaZ6R6sXexk5Z64bCgo2TYyn760EdcQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="{{url_for('static',filename='js/main.js')}}"></script>
</body>
</html>

app/user/templates/user/index_user.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5 ">
    
 
        <div class="row">
              <div class="col-md-8 offset-md-2 ">
        
          
        <h1 class="display-4 text-center">¡Bienvenido a Horus! </h1>
        
        
        
          
        <p class="lead text-justify">Acaba de acceder al servidor de Horus, especializado en diagnósticos por imagen mediante el uso de inteligencia artificial. Estamos encantados de tenerlo.</p>
        
                
        
          
        <p class="lead text-justify">En la pestaña de servicios, puede explorar los distintos diagnósticos que ofrecemos. Si el paciente no tiene historial médico en nuestro servidor, le recomendamos registrarlos en la pestaña de paciente.</p>
        
                
        
         
        <p class="lead text-justify">Ante cualquier duda sobre el funcionamiento del servidor o si desea realizar aportes, no dude en comunicarse con nuestro soporte técnico.</p>
        
                <p class="lead text-justify">Si es un médico especialista, por favor, contáctenos para otorgarle el rango correspondiente y permitirle realizar aportes adicionales.</p>
        
                
        
                
        <p class="lead text-justify">Gracias por confiar en Horus para sus necesidades de diagnóstico por imagen.</p>
        
              
        
              
              </div>
        </div>
</div>
  {% endblock %}

app/user/templates/user/ingresar.html
{%from "macros.html" import get_menssages%}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col">
                <div class="text-end">
                        
                 <h2 class="fw-bold text-center py-5">Bienvenido</h2>

                 <!--Form -->
                 <form action=""  method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-4">
                       <div class="text-start"> {{ form.email.label(class_="form-label")}}  </div>
                        {{ form.email(class_="form-control",placeholder='Email de usuario')}}  
                        {% for error in form.email.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="mb-4">
                        <div class="text-start">{{ form.password.label(class_="form-label")}}</div>
                        {{ form.password (class_="form-control",placeholder='Contraseña') }}
                        {% for error in form.password.errors %}
                        <span style="color: red;">{{ error }}</span>
                        {% endfor %}
                    </div>
                    <div class="mb-4 form-check">
                        {{ form.remember_me.label (class_="form-check-label")}}
                        {{ form.remember_me(class_="form-check-input") }} 
                        
                    </div>
                    <div class="d-grid">
                        {{ form.submit(class_="btn btn-primary") }}

                    </div>
                    <div class="my-3">
                        <span>¿No tienes cuenta ? <a href="{{url_for('user.registrar')}}">Regístrate</a></span>
                        <br>
                        <span><a href="#">Recuperar Password</a></span>
                    </div>
                 </form>

               
                </div>
            </div>


            <div class="col">

            </div>
        </div>



    </div>


         
    
{% endblock %}

app/user/templates/user/registrar.html
{%from "macros.html" import get_menssages%}
{% extends "base.html" %}
{% block title %}Registro de usuarios{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col">
                <div class="text-end">
                        
                 <h2 class="fw-bold text-center py-5">Bienvenido</h2>

                 <!--Form -->
                 <form action=""  method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-4">
                       <div class="text-start"> {{ form.name.label(class_="form-label")}}  </div>
                       {{ form.name(class_="form-control",placeholder='Nombre') }}
                       {% for error in form.name.errors %}
                       <span style="color: red;">{{ error }}</span>
                       {% endfor %}
                    </div>
                    <div class="mb-4">
                        <div class="text-start">{{ form.email.label(class_="form-label")}}</div>
                        {{ form.email(class_="form-control",placeholder='Correo') }}
                        {% for error in form.name.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
                    </div>


                    <div class="mb-4">
                        <div class="text-start">{{ form.password.label(class_="form-label")}}</div>
                        {{ form.password(class_="form-control",placeholder='Contraseña') }}
                        {% for error in form.name.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    </div>
               


                    <div class="mb-4">
                        <div class="text-start form-label">Profesión</div>
                        {{ form.usuario_profesion(class_="form-control") }}
                    </div>
                    <div class="d-grid">
                        {{ form.submit(class_="btn btn-primary") }}

                    </div>
                    <div class="my-3">
                        <span>ya tienes cuenta <a href="{{url_for('user.login')}}">Ingresa</a></span>
                        
                    </div>
                 </form>

              
                </div>
            </div>


            <div class="col">

            </div>
        </div>



    </div>




</div>
{% endblock %}

app/user/templates/user/signup_form.html
{% extends "base.html" %}



{% block title %}Registro de usuarios{% endblock %}

{% block content %}
<div class="registro">
    {% if error %}
    <div class="container-fluid">
        <div class="alert alert-danger alert-dismissible">
            <button class="btn-close" data-bs-dismiss="alert"></button>
            {{ error }}
     <a class="alert-link" href="{{ url_for('user.login') }}"">Presione aquí para ingresar</a>
    
    </div>
    </div>
    {% endif %}

    <div class="container">
        <div class="row">
            <div class="col">

            </div>
            <div class="col">
                <div class="text-end">
                        
                 <h2 class="fw-bold text-center py-5">Bienvenido</h2>

                 <!--Form -->
                 <form action=""  method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-4">
                       <div class="text-start"> {{ form.name.label(class_="form-label")}}  </div>
                       {{ form.name(class_="form-control",placeholder='Nombre') }}
                       {% for error in form.name.errors %}
                       <span style="color: red;">{{ error }}</span>
                       {% endfor %}
                    </div>
                    <div class="mb-4">
                        <div class="text-start">{{ form.email.label(class_="form-label")}}</div>
                        {{ form.email(class_="form-control",placeholder='Correo') }}
                        {% for error in form.name.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
                    </div>


                    <div class="mb-4">
                        <div class="text-start">{{ form.password.label(class_="form-label")}}</div>
                        {{ form.password(class_="form-control",placeholder='Contraseña') }}
                        {% for error in form.name.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    </div>
               


                    <div class="mb-4">
                        <div class="text-start form-label">Profesión</div>
                        {{ form.usuario_profesion(class_="form-control") }}
                    </div>
                    <div class="d-grid">
                        {{ form.submit(class_="btn btn-primary") }}

                    </div>
                    <div class="my-3">
                        <span>ya tienes cuenta <a href="{{url_for('user.login')}}">Ingresa</a></span>
                        
                    </div>
                 </form>

              
                </div>
            </div>


            <div class="col">

            </div>
        </div>



    </div>




</div>
{% endblock %}